=== theisegoria/NPCVoice/docs/schema/speech-info.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "npc_audio.info_json (npc_speech_speak)",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "phonemes",
    "duration",
    "sourceLUFS",
    "gainDB",
    "unknownWords",
    "visemes",
    "phonemeTrack"
  ],
  "properties": {
    "phonemes": {
      "type": "string"
    },
    "duration": {
      "type": "number",
      "minimum": 0
    },
    "sourceLUFS": {
      "type": "number"
    },
    "gainDB": {
      "type": "number"
    },
    "unknownWords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "visemes": {
      "type": "array",
      "items": {
        "$ref": "common.schema.json#/$defs/visemeSegment"
      }
    },
    "phonemeTrack": {
      "type": "array",
      "items": {
        "$ref": "common.schema.json#/$defs/phonemeSegment"
      }
    }
  }
}

=== theisegoria/NPCVoice/Tests/NPCKitTests/Fixtures/speech-info.json
{"sourceLUFS":-25.16416573806718,"duration":6.625,"phonemes":"ˈivnɪŋ, lˈʌv. ɐ ɹˈum æt ðə sˈɔltɹɛn ˈɛnd kˈɔsts θɹˈi sˈɪlvəɹ mˈɑɹks ɐ nˈIt. bɹˈɛkfəst ɪz ˈɛkstɹə.","visemes":[{"end":0.375,"start":0,"viseme":"sil","weight":1},{"end":0.525,"start":0.375,"viseme":"ih","weight":1},{"end":0.575,"start":0.525,"viseme":"FF","weight":1},{"end":0.65,"start":0.575,"viseme":"DD","weight":1},{"end":0.75,"start":0.65,"viseme":"ih","weight":1},{"end":0.825,"start":0.75,"viseme":"kk","weight":1},{"end":0.95,"start":0.825,"viseme":"sil","weight":0.5},{"end":1,"start":0.95,"viseme":"DD","weight":1},{"end":1.25,"start":1,"viseme":"aa","weight":1},{"end":1.6,"start":1.25,"viseme":"FF","weight":1},{"end":1.775,"start":1.6,"viseme":"sil","weight":1},{"end":1.875,"start":1.775,"viseme":"aa","weight":1},{"end":1.9,"start":1.875,"viseme":"RR","weight":1},{"end":2,"start":1.9,"viseme":"ou","weight":1},{"end":2.05,"start":2,"viseme":"PP","weight":1},{"end":2.075,"start":2.05,"viseme":"E","weight":1},{"end":2.125,"start":2.075,"viseme":"DD","weight":1},{"end":2.15,"start":2.125,"viseme":"TH","weight":1},{"end":2.225,"start":2.15,"viseme":"aa","weight":1},{"end":2.275,"start":2.225,"viseme":"SS","weight":1},{"end":2.375,"start":2.275,"viseme":"oh","weight":1},{"end":2.475,"start":2.375,"viseme":"DD","weight":1},{"end":2.525,"start":2.475,"viseme":"RR","weight":1},{"end":2.575,"start":2.525,"viseme":"E","weight":1},{"end":2.675,"start":2.575,"viseme":"DD","weight":1},{"end":2.8,"start":2.675,"viseme":"E","weight":1},{"end":2.95,"start":2.8,"viseme":"DD","weight":1},{"end":3,"start":2.95,"viseme":"kk","weight":1},{"end":3.125,"start":3,"viseme":"oh","weight":1},{"end":3.175,"start":3.125,"viseme":"SS","weight":1},{"end":3.225,"start":3.175,"viseme":"DD","weight":1},{"end":3.275,"start":3.225,"viseme":"SS","weight":1},{"end":3.35,"start":3.275,"viseme":"sil","weight":0.5},{"end":3.4,"start":3.35,"viseme":"TH","weight":1},{"end":3.45,"start":3.4,"viseme":"RR","weight":1},{"end":3.575,"start":3.45,"viseme":"ih","weight":1},{"end":3.65,"start":3.575,"viseme":"sil","weight":0.5},{"end":3.7,"start":3.65,"viseme":"SS","weight":1},{"end":3.8,"start":3.7,"viseme":"ih","weight":1},{"end":3.85,"start":3.8,"viseme":"DD","weight":1},{"end":3.9,"start":3.85,"viseme":"FF","weight":1},{"end":3.95,"start":3.9,"viseme":"aa","weight":1},{"end":4.05,"start":3.95,"viseme":"RR","weight":1},{"end":4.075,"start":4.05,"viseme":"PP","weight":1},{"end":4.15,"start":4.075,"viseme":"aa","weight":1},{"end":4.2,"start":4.15,"viseme":"RR","weight":1},{"end":4.25,"start":4.2,"viseme":"kk","weight":1},{"end":4.3,"start":4.25,"viseme":"SS","weight":1},{"end":4.375,"start":4.3,"viseme":"aa","weight":1},{"end":4.4,"start":4.375,"viseme":"DD","weight":1},{"end":4.52,"start":4.4,"viseme":"aa","weight":1},{"end":4.6,"start":4.52,"viseme":"ih","weight":1},{"end":4.875,"start":4.6,"viseme":"DD","weight":1},{"end":5.05,"start":4.875,"viseme":"sil","weight":1},{"end":5.1,"start":5.05,"viseme":"PP","weight":1},{"end":5.125,"start":5.1,"viseme":"RR","weight":1},{"end":5.225,"start":5.125,"viseme":"E","weight":1},{"end":5.3,"start":5.225,"viseme":"kk","weight":1},{"end":5.375,"start":5.3,"viseme":"FF","weight":1},{"end":5.45,"start":5.375,"viseme":"aa","weight":1},{"end":5.5,"start":5.45,"viseme":"SS","weight":1},{"end":5.6,"start":5.5,"viseme":"DD","weight":1},{"end":5.65,"start":5.6,"viseme":"ih","weight":1},{"end":5.7,"start":5.65,"viseme":"SS","weight":1},{"end":5.775,"start":5.7,"viseme":"sil","weight":0.5},{"end":5.875,"start":5.775,"viseme":"E","weight":1},{"end":5.925,"start":5.875,"viseme":"kk","weight":1},{"end":5.975,"start":5.925,"viseme":"SS","weight":1},{"end":6.025,"start":5.975,"viseme":"DD","weight":1},{"end":6.1,"start":6.025,"viseme":"RR","weight":1},{"end":6.425,"start":6.1,"viseme":"aa","weight":1},{"end":6.625,"start":6.425,"viseme":"sil","weight":1}],"phonemeTrack":[{"end":0.375,"start":0,"source":"","stress":"unspecified","phoneme":"sil"},{"end":0.525,"start":0.375,"source":"ˈi","stress":"primary","phoneme":"IY"},{"end":0.575,"start":0.525,"source":"v","stress":"unspecified","phoneme":"V"},{"end":0.65,"start":0.575,"source":"n","stress":"unspecified","phoneme":"N"},{"end":0.75,"start":0.65,"source":"ɪ","stress":"unspecified","phoneme":"IH"},{"end":0.825,"start":0.75,"source":"ŋ","stress":"unspecified","phoneme":"NG"},{"end":0.95,"start":0.825,"source":"","stress":"unspecified","phoneme":"sp"},{"end":1,"start":0.95,"source":"l","stress":"unspecified","phoneme":"L"},{"end":1.25,"start":1,"source":"ˈʌ","stress":"primary","phoneme":"AH"},{"end":1.6,"start":1.25,"source":"v","stress":"unspecified","phoneme":"V"},{"end":1.775,"start":1.6,"source":"","stress":"unspecified","phoneme":"sil"},{"end":1.875,"start":1.775,"source":"ɐ","stress":"unstressed","phoneme":"AH"},{"end":1.9,"start":1.875,"source":"ɹ","stress":"unspecified","phoneme":"R"},{"end":2,"start":1.9,"source":"ˈu","stress":"primary","phoneme":"UW"},{"end":2.05,"start":2,"source":"m","stress":"unspecified","phoneme":"M"},{"end":2.075,"start":2.05,"source":"æ","stress":"unspecified","phoneme":"AE"},{"end":2.125,"start":2.075,"source":"t","stress":"unspecified","phoneme":"T"},{"end":2.15,"start":2.125,"source":"ð","stress":"unspecified","phoneme":"DH"},{"end":2.225,"start":2.15,"source":"ə","stress":"unstressed","phoneme":"AH"},{"end":2.275,"start":2.225,"source":"s","stress":"unspecified","phoneme":"S"},{"end":2.375,"start":2.275,"source":"ˈɔ","stress":"primary","phoneme":"AO"},{"end":2.425,"start":2.375,"source":"l","stress":"unspecified","phoneme":"L"},{"end":2.475,"start":2.425,"source":"t","stress":"unspecified","phoneme":"T"},{"end":2.525,"start":2.475,"source":"ɹ","stress":"unspecified","phoneme":"R"},{"end":2.575,"start":2.525,"source":"ɛ","stress":"unspecified","phoneme":"EH"},{"end":2.675,"start":2.575,"source":"n","stress":"unspecified","phoneme":"N"},{"end":2.8,"start":2.675,"source":"ˈɛ","stress":"primary","phoneme":"EH"},{"end":2.85,"start":2.8,"source":"n","stress":"unspecified","phoneme":"N"},{"end":2.95,"start":2.85,"source":"d","stress":"unspecified","phoneme":"D"},{"end":3,"start":2.95,"source":"k","stress":"unspecified","phoneme":"K"},{"end":3.125,"start":3,"source":"ˈɔ","stress":"primary","phoneme":"AO"},{"end":3.175,"start":3.125,"source":"s","stress":"unspecified","phoneme":"S"},{"end":3.225,"start":3.175,"source":"t","stress":"unspecified","phoneme":"T"},{"end":3.275,"start":3.225,"source":"s","stress":"unspecified","phoneme":"S"},{"end":3.35,"start":3.275,"source":"","stress":"unspecified","phoneme":"sp"},{"end":3.4,"start":3.35,"source":"θ","stress":"unspecified","phoneme":"TH"},{"end":3.45,"start":3.4,"source":"ɹ","stress":"unspecified","phoneme":"R"},{"end":3.575,"start":3.45,"source":"ˈi","stress":"primary","phoneme":"IY"},{"end":3.65,"start":3.575,"source":"","stress":"unspecified","phoneme":"sp"},{"end":3.7,"start":3.65,"source":"s","stress":"unspecified","phoneme":"S"},{"end":3.8,"start":3.7,"source":"ˈɪ","stress":"primary","phoneme":"IH"},{"end":3.85,"start":3.8,"source":"l","stress":"unspecified","phoneme":"L"},{"end":3.9,"start":3.85,"source":"v","stress":"unspecified","phoneme":"V"},{"end":3.95,"start":3.9,"source":"ə","stress":"unstressed","phoneme":"AH"},{"end":4.05,"start":3.95,"source":"ɹ","stress":"unspecified","phoneme":"R"},{"end":4.075,"start":4.05,"source":"m","stress":"unspecified","phoneme":"M"},{"end":4.15,"start":4.075,"source":"ˈɑ","stress":"primary","phoneme":"AA"},{"end":4.2,"start":4.15,"source":"ɹ","stress":"unspecified","phoneme":"R"},{"end":4.25,"start":4.2,"source":"k","stress":"unspecified","phoneme":"K"},{"end":4.3,"start":4.25,"source":"s","stress":"unspecified","phoneme":"S"},{"end":4.375,"start":4.3,"source":"ɐ","stress":"unstressed","phoneme":"AH"},{"end":4.4,"start":4.375,"source":"n","stress":"unspecified","phoneme":"N"},{"end":4.6,"start":4.4,"source":"ˈI","stress":"primary","phoneme":"AY"},{"end":4.875,"start":4.6,"source":"t","stress":"unspecified","phoneme":"T"},{"end":5.05,"start":4.875,"source":"","stress":"unspecified","phoneme":"sil"},{"end":5.1,"start":5.05,"source":"b","stress":"unspecified","phoneme":"B"},{"end":5.125,"start":5.1,"source":"ɹ","stress":"unspecified","phoneme":"R"},{"end":5.225,"start":5.125,"source":"ˈɛ","stress":"primary","phoneme":"EH"},{"end":5.3,"start":5.225,"source":"k","stress":"unspecified","phoneme":"K"},{"end":5.375,"start":5.3,"source":"f","stress":"unspecified","phoneme":"F"},{"end":5.45,"start":5.375,"source":"ə","stress":"unstressed","phoneme":"AH"},{"end":5.5,"start":5.45,"source":"s","stress":"unspecified","phoneme":"S"},{"end":5.6,"start":5.5,"source":"t","stress":"unspecified","phoneme":"T"},{"end":5.65,"start":5.6,"source":"ɪ","stress":"unspecified","phoneme":"IH"},{"end":5.7,"start":5.65,"source":"z","stress":"unspecified","phoneme":"Z"},{"end":5.775,"start":5.7,"source":"","stress":"unspecified","phoneme":"sp"},{"end":5.875,"start":5.775,"source":"ˈɛ","stress":"primary","phoneme":"EH"},{"end":5.925,"start":5.875,"source":"k","stress":"unspecified","phoneme":"K"},{"end":5.975,"start":5.925,"source":"s","stress":"unspecified","phoneme":"S"},{"end":6.025,"start":5.975,"source":"t","stress":"unspecified","phoneme":"T"},{"end":6.1,"start":6.025,"source":"ɹ","stress":"unspecified","phoneme":"R"},{"end":6.425,"start":6.1,"source":"ə","stress":"unstressed","phoneme":"AH"},{"end":6.625,"start":6.425,"source":"","stress":"unspecified","phoneme":"sil"}],"unknownWords":[],"gainDB":2.1641657380671795}
